questions = [
    # Einfache Fragen
    {
        "frage": "Welches PowerShell-Cmdlet wird verwendet, um eine neue virtuelle Maschine zu erstellen?",
        "antworten": ["New-VM", "Get-VM", "Remove-VM", "Set-VM"],
        "richtige_antwort_index": 0,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Was ist ein gängiges Dateiformat für Konfigurationsdaten in Python-Anwendungen?",
        "antworten": ["XML", "CSV", "TXT", "JSON"],
        "richtige_antwort_index": 3,
        "thema": "Python",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welches Python-Keyword wird verwendet, um eine Funktion zu definieren?",
        "antworten": ["func", "def", "function", "define"],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welches Kommando listet in PowerShell alle laufenden Prozesse auf?",
        "antworten": ["Get-Process", "List-Process", "Show-Process", "Find-Process"],
        "richtige_antwort_index": 0,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Was bedeutet die Abkürzung 'VM'?",
        "antworten": [
            "Virtual Memory",
            "Virtual Machine",
            "Very Modern",
            "Visual Machine",
        ],
        "richtige_antwort_index": 1,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welcher Datentyp wird in Python für eine geordnete und veränderbare Sammlung von Elementen verwendet?",
        "antworten": ["Tuple", "Set", "Dictionary", "List"],
        "richtige_antwort_index": 3,
        "thema": "Python",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welches Symbol wird in Python für einzeilige Kommentare verwendet?",
        "antworten": ["//", "#", "/* */", "<!-- -->"],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welches PowerShell-Cmdlet wird verwendet, um den Inhalt einer Datei zu lesen?",
        "antworten": ["Read-Content", "Get-File", "Show-Text", "Get-Content"],
        "richtige_antwort_index": 3,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Was ist ein 'Host-System' im Kontext der Virtualisierung?",
        "antworten": [
            "Das Gast-Betriebssystem",
            "Die virtuelle Maschine",
            "Das physische Betriebssystem, auf dem der Hypervisor läuft",
            "Ein Remote-Server",
        ],
        "richtige_antwort_index": 2,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "einfach",
    },
    {
        "frage": "Welches Keyword wird in Python verwendet, um eine Schleife zu beenden?",
        "antworten": ["stop", "exit", "break", "end"],
        "richtige_antwort_index": 2,
        "thema": "Python",
        "schwierigkeitsgrad": "einfach",
    },
    # Mittlere Fragen
    {
        "frage": "Was ist der Hauptvorteil von Virtualisierung?",
        "antworten": [
            "Erhöhte Hardwarekosten",
            "Weniger Flexibilität",
            "Bessere Hardwareauslastung",
            "Nur ein Betriebssystem pro Server",
        ],
        "richtige_antwort_index": 2,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist ein Hypervisor Typ 1?",
        "antworten": [
            "Läuft auf einem Host-Betriebssystem",
            "Wird auch als 'Bare-Metal' bezeichnet",
            "Benötigt eine grafische Benutzeroberfläche",
            "Ist langsamer als Typ 2",
        ],
        "richtige_antwort_index": 1,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist der Zweck der PowerShell Execution Policy?",
        "antworten": [
            "Sie bestimmt, welche Benutzer PowerShell verwenden dürfen",
            "Sie steuert, welche Skripte ausgeführt werden dürfen",
            "Sie legt die maximale Speichernutzung fest",
            "Sie konfiguriert die Netzwerkverbindung",
        ],
        "richtige_antwort_index": 1,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist ein 'Snapshot' einer virtuellen Maschine?",
        "antworten": [
            "Eine vollständige Kopie der VM-Festplatte",
            "Ein gespeicherter Zustand der VM zu einem bestimmten Zeitpunkt",
            "Ein Backup des Host-Systems",
            "Ein Protokoll der VM-Aktivitäten",
        ],
        "richtige_antwort_index": 1,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist der Unterschied zwischen einer Liste und einem Tupel in Python?",
        "antworten": [
            "Listen sind veränderbar, Tupel sind unveränderbar",
            "Tupel sind veränderbar, Listen sind unveränderbar",
            "Es gibt keinen Unterschied",
            "Listen können nur Zahlen enthalten",
        ],
        "richtige_antwort_index": 0,
        "thema": "Python",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Welches PowerShell-Cmdlet wird verwendet, um Objekte nach einer Eigenschaft zu sortieren?",
        "antworten": ["Sort-Object", "Order-By", "Arrange-Items", "Group-Object"],
        "richtige_antwort_index": 0,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist der Unterschied zwischen NAT und Bridged Networking bei VMs?",
        "antworten": [
            "NAT teilt die IP des Hosts, Bridged erhält eine eigene IP im Netzwerk",
            "Bridged teilt die IP des Hosts, NAT erhält eine eigene IP",
            "Es gibt keinen Unterschied",
            "NAT ist schneller",
        ],
        "richtige_antwort_index": 0,
        "thema": "VM-Konzepte",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was bewirkt `pip` im Python-Ökosystem?",
        "antworten": [
            "Es führt Python-Skripte aus",
            "Es ist ein Texteditor für Python",
            "Es ist der Standard-Paketmanager",
            "Es debuggt Python-Code",
        ],
        "richtige_antwort_index": 2,
        "thema": "Python",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Wie kann man in PowerShell einen neuen Dienst erstellen?",
        "antworten": [
            "Make-Service",
            "Create-Service",
            "New-Service",
            "Install-Service",
        ],
        "richtige_antwort_index": 2,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "mittel",
    },
    {
        "frage": "Was ist 'P2V'-Migration?",
        "antworten": [
            "Virtual to Physical",
            "Physical to Virtual",
            "Python to VBScript",
            "PowerShell to Virtual",
        ],
        "richtige_antwort_index": 1,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "mittel",
    },
    # Schwere Fragen
    {
        "frage": "Welche der folgenden Komponenten gehört NICHT zu einem Active Directory Domain Services (AD DS)?",
        "antworten": ["Domänencontroller", "Schema", "Globaler Katalog", "DHCP-Server"],
        "richtige_antwort_index": 3,
        "thema": "VM-Konzepte",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was beschreibt 'Polymorphismus' in der objektorientierten Programmierung?",
        "antworten": [
            "Das Verstecken von komplexen Implementierungsdetails",
            "Die Fähigkeit einer Variable, viele Formen anzunehmen",
            "Das Bündeln von Daten und Methoden in einer Klasse",
            "Die Ableitung von Klassen von anderen Klassen",
        ],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist 'Desired State Configuration' (DSC) in PowerShell?",
        "antworten": [
            "Ein Werkzeug zur Skripterstellung",
            "Ein Framework zur deklarativen Konfiguration von Systemen",
            "Eine Methode zur Leistungsüberwachung",
            "Ein Sicherheitsprotokoll",
        ],
        "richtige_antwort_index": 1,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist der 'Global Catalog' in einem Active Directory?",
        "antworten": [
            "Eine Liste aller Computer in der Domäne",
            "Ein schreibgeschützter, teilweiser Replikat aller Objekte im Forest",
            "Der primäre Domänencontroller",
            "Ein Backup aller Benutzerkonten",
        ],
        "richtige_antwort_index": 1,
        "thema": "VM-Konzepte",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist ein 'Decorator' in Python?",
        "antworten": [
            "Eine Klasse zur Gestaltung von GUIs",
            "Eine Funktion, die eine andere Funktion modifiziert oder erweitert",
            "Ein spezieller Variablentyp",
            "Ein Kommentarstil",
        ],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist der Unterschied zwischen `Invoke-Command` und `Enter-PSSession`?",
        "antworten": [
            "`Invoke-Command` führt einen Befehl remote aus, `Enter-PSSession` startet eine interaktive Sitzung",
            "Es gibt keinen Unterschied",
            "`Enter-PSSession` ist veraltet",
            "`Invoke-Command` ist nur für lokale Befehle",
        ],
        "richtige_antwort_index": 0,
        "thema": "PowerShell",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist 'Memory Overcommitment' bei Hypervisoren?",
        "antworten": [
            "Das Zuweisen von mehr RAM an VMs als physisch vorhanden ist",
            "Das Löschen von ungenutztem RAM",
            "Ein Fehlerzustand des Speichers",
            "Die Komprimierung des RAMs",
        ],
        "richtige_antwort_index": 0,
        "thema": "Virtualisierung",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist die 'Global Interpreter Lock' (GIL) in CPython?",
        "antworten": [
            "Ein Sicherheitsfeature, das den Code sperrt",
            "Ein Mechanismus, der verhindert, dass mehrere Threads gleichzeitig Python-Bytecode ausführen",
            "Ein Werkzeug zur globalen Variablendeklaration",
            "Eine Methode zur Code-Verschlüsselung",
        ],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Was ist eine 'FSMO-Rolle' (Flexible Single Master Operation) im Active Directory?",
        "antworten": [
            "Eine spezielle Rolle, die nur ein Domänencontroller im Forest oder in der Domäne innehaben kann",
            "Eine Rolle für jeden Benutzer",
            "Eine Sicherheitsgruppe",
            "Eine Richtlinie für Dateizugriffe",
        ],
        "richtige_antwort_index": 0,
        "thema": "VM-Konzepte",
        "schwierigkeitsgrad": "schwer",
    },
    {
        "frage": "Erkläre den Zweck von `__init__.py` in einem Python-Paket.",
        "antworten": [
            "Es enthält den Hauptcode des Pakets",
            "Es markiert ein Verzeichnis als Python-Paket und kann Initialisierungscode ausführen",
            "Es ist eine Konfigurationsdatei",
            "Es löscht das Paket bei Deinstallation",
        ],
        "richtige_antwort_index": 1,
        "thema": "Python",
        "schwierigkeitsgrad": "schwer",
    },
]
